Dataset: ZINC
Model: GCN
device: cpu
model_path: /samplesize_models/ot_fusion_ZINC_sinkhorn_100_quadratic_energy_100samples.pkl
net_params:
  L: 4
  assign_dim: -185
  avg_node_num: 24
  batch_norm: true
  batch_size: 5
  cat: false
  data_mode: default
  depth_of_mlp: 2
  dropout: 0.0
  edge_feat: false
  embedding_dim: -1
  gated: false
  gnn_per_block: -1
  gpu_id: -1
  hidden_dim: 145
  in_feat_dropout: 0.0
  kernel: -1
  layer_norm: true
  learn_eps_GIN: true
  linkpred: true
  n_heads: -1
  n_mlp_GIN: -1
  neighbor_aggr_GIN: sum
  num_atom_type: 28
  num_bond_type: 4
  num_pool: 1
  out_dim: 145
  pool_ratio: -1
  pos_enc: true
  pos_enc_dim: 8
  pseudo_dim_MoNet: -1
  radius: 2
  readout: sum
  residual: true
  sage_aggregator: meanpool
  self_loop: false
params:
  batch_size: 5
  epochs: 4
  init_lr: 5.0e-05
  lr_reduce_factor: 0.3
  lr_schedule_patience: 25
  max_time: 1
  min_lr: 1.0e-06
  print_epoch_interval: 5
  seed: 41
  weight_decay: 0
total_param: 103077
