GCN_ZINC_GPU-1_00h27m39s_on_Dec_31_2023_cp:
  Dataset: ZINC
  Model: GCN
  model_path: GCN_ZINC_GPU-1_00h27m39s_on_Dec_31_2023_cp/final.pkl
  net_params:
    L: 4
    assign_dim: -4736
    avg_node_num: 24
    batch_norm: true
    batch_size: 128
    cat: false
    data_mode: default
    depth_of_mlp: 2
    dropout: 0.0
    edge_feat: false
    embedding_dim: -1
    gated: false
    gnn_per_block: -1
    gpu_id: -1
    hidden_dim: 145
    in_feat_dropout: 0.0
    kernel: -1
    layer_norm: true
    learn_eps_GIN: true
    linkpred: true
    n_heads: -1
    n_mlp_GIN: -1
    neighbor_aggr_GIN: sum
    num_atom_type: 28
    num_bond_type: 4
    num_pool: 1
    out_dim: 145
    pool_ratio: -1
    pos_enc: true
    pos_enc_dim: 8
    pseudo_dim_MoNet: -1
    radius: 2
    readout: sum
    residual: true
    sage_aggregator: meanpool
    self_loop: false
  params:
    batch_size: 128
    epochs: 1000
    init_lr: 0.001
    lr_reduce_factor: 0.5
    lr_schedule_patience: 10
    max_time: 12
    min_lr: 1.0e-05
    print_epoch_interval: 5
    seed: 41
    weight_decay: 0
  total_param: 103077
