wandb: False
wandb_entity: deep-talk
wandb_project: GCN_Fusion

# Paths 
models_dir: ../../../models
individual_models_dir: ${models_dir}/individual_models/
experiment_models_dir: /fused_models/

dataset_dir: ../../../gnn_benchmarking/data/molecules/
#dataset_dir: ../../../gnn_benchmarking/data/superpixels/
dataset: '?' # filled in automatically

# Each experiment should specify this path to its folder, dummy folder if not specified
models_conf_dir: ../../../src/conf/models/fused_models/

# File names
vanilla_model_save_path : ${models_dir}/fused_models/vanilla_avg/vanilla.pkl
otFused_model_save_path : ${models_dir}/fused_models/ot_fusion/otFused.pkl

defaults:
  - _self_
  #- ot: config_ot
  - optimal_transport: sinkhorn
  - ground_cost_mlp: v_sidak
  - ground_cost_gcn: v_1
  - graph_cost: feature_lp
  # The first model in below list is the target one
  - models/individual_models:
      - GCN_ZINC_GPU-1_19h03m35s_on_Jan_06_2024 # GCN no batchnorm
      - GCN_ZINC_GPU-1_19h18m15s_on_Jan_06_2024 # GCN no batchnorm
#      - MLP_ZINC_GPU-1_19h35m55s_on_Jan_06_2024 # big MLPs (similar size to our gcns)
#      - MLP_ZINC_GPU-1_19h46m10s_on_Jan_06_2024 # big MLPs
#      - MLP_ZINC_GPU-1_20h13m48s_on_Jan_06_2024 # smaller MLPs
#      - MLP_ZINC_GPU-1_20h16m58s_on_Jan_06_2024 # smaller MLPs
#      - GCN_MNIST_GPU0_21h12m06s_on_Jan_04_2024 # full mnist
#      - GCN_MNIST_GPU1_21h12m06s_on_Jan_04_2024 # full mnist
#      - GCN_MNIST_GPU-1_11h04m16s_on_Jan_05_2024 # 1 conv full data
#      - GCN_MNIST_GPU-1_11h39m56s_on_Jan_05_2024 # 1 conv full data
#      - GCN_MNIST_GPU-1_00h59m21s_on_Jan_05_2024 # full data, seed 14
#      - GCN_MNIST_GPU-1_21h29m21s_on_Jan_04_2024 # no 4s full data, seed 41
#      - GCN_MNIST_GPU-1_22h51m52s_on_Jan_05_2024
#      - GCN_MNIST_GPU-1_23h59m47s_on_Jan_04_2024 # no 4s small data, seed 14
#      - GCN_ZINC_GPU-1_01h01m17s_on_Jan_02_2024 # model for sweep
#      - GCN_ZINC_GPU-1_01h08m48s_on_Jan_02_2024 # model for sweep
#      - GCN_ZINC_GPU-1_20h32m34s_on_Jan_01_2024 # small for quick testing
#      - GCN_ZINC_GPU-1_21h05m43s_on_Jan_01_2024 # small for quick testing
#      - GCN_ZINC_GPU-1_20h33m52s_on_Jan_01_2024_cp # small for quick testinf
#       - GCN_ZINC_GPU-1_00h24m41s_on_Jan_02_2024 # only convnets and mlps no act
#       - GCN_ZINC_GPU-1_00h25m09s_on_Jan_02_2024 # only convnets and mlps no act
#       - GCN_ZINC_GPU-1_00h46m59s_on_Jan_02_2024 # only convnets mlps bn act
#       - GCN_ZINC_GPU-1_00h47m38s_on_Jan_02_2024 # only convnets mlps bn act
#       - GCN_ZINC_GPU-1_00h42m35s_on_Jan_02_2024 # only convnets mlps with act
#       - GCN_ZINC_GPU-1_00h42m57s_on_Jan_02_2024 # only convnets mlps with act
#       - GCN_ZINC_GPU-1_00h52m04s_on_Jan_02_2024 # only convnets mlps with act and residual <- this brakes
#       - GCN_ZINC_GPU-1_00h53m17s_on_Jan_02_2024 # only convnets mlps bn act
#      - GCN_ZINC_GPU-1_00h59m00s_on_Jan_02_2024 # just without residuals
#      - GCN_ZINC_GPU-1_00h57m30s_on_Jan_02_2024 # just without residuals


acts_from_bn: True # Take batch normalised activations
fast_l2: False # Will vectorize the graphs and treat convnets as mlps
take_single_vertex_acts: False # Needs an extra change in PyTorch code and setting a flag in benchmarking: gcn_layer.py
save_aligned: True
deterministic: True
hydra_base_dir: ""
device: cpu
batch_size: 100
num_batches: 1
gw_batch_scaling: 1
geom_ensemble_type: acts # acts or weights
gpu_id: -1
# Whether to update the activations after aligning the weights
update_acts: True
# Whether to compute the histogram based on weight importance
importance: False
# Whether to return a normalised histogram
unbalanced: False
skip_last_layer: True
ensemble_step: 0.5
skip_last_layer_type: 'average' # or 'second'
correction: True
debug: True
past_correction: True
width_ratio: 1
ot_fusions_per_model: 5

# Fine tuning fused models
fine_tune: True
fine_tune_epochs: 40
fine_tune_save_step: 20

