wandb: False
wandb_entity: deep-talk
wandb_project: GCN_Fusion

# Config Directory:
config_dir: ../../../src/conf/models/fused_models/

# Models path 
models_dir: ../../../models

write_to_csv: True
results_dir: ../../../results/
results_file: optimization_MAE.csv
evaluate_in_place: False
ensemble: True

Dataset: [ "ZINC" ]
dataset_dir: ../../../gnn_benchmarking/data/molecules/
#Dataset: ["MNIST"]
#dataset_dir: ../../../gnn_benchmarking/data/superpixels/

device: "cpu"
hydra_base_dir: ""