wandb: False
wandb_entity: deep-talk
wandb_project: GCN_Fusion

# Paths 
models_dir: ../../../models
individual_models_dir: ${models_dir}/individual_models/
experiment_models_dir: /fused_models/
dataset_dir: ../../../gnn_benchmarking/data/molecules/

# Each experiment should specify this path to its folder, dummy folder if not specified
models_conf_dir: ../../../src/conf/models/fused_models/

# File names
vanilla_model_save_path : ${models_dir}/fused_models/vanilla_avg/vanilla.pkl
otFused_model_save_path : ${models_dir}/fused_models/ot_fusion/otFused.pkl

defaults:
  - _self_
  #- ot: config_ot
  - optimal_transport: emd
  - ground_cost_mlp: v_sidak
  - ground_cost_gcn: v_1
  - graph_cost: feature_lp
  # The first model in below list is the target one
  - models/individual_models:
      - GCN_ZINC_GPU-1_01h01m17s_on_Jan_02_2024
      - GCN_ZINC_GPU-1_01h08m48s_on_Jan_02_2024
#      - GCN_ZINC_GPU-1_20h32m34s_on_Jan_01_2024 # small for quick testing
#      - GCN_ZINC_GPU-1_21h05m43s_on_Jan_01_2024 # small for quick testing
#      - GCN_ZINC_GPU-1_20h33m52s_on_Jan_01_2024_cp # small for quick testinf
#       - GCN_ZINC_GPU-1_00h24m41s_on_Jan_02_2024 # only convnets and mlps no act
#       - GCN_ZINC_GPU-1_00h25m09s_on_Jan_02_2024 # only convnets and mlps no act
#       - GCN_ZINC_GPU-1_00h46m59s_on_Jan_02_2024 # only convnets mlps bn act
#       - GCN_ZINC_GPU-1_00h47m38s_on_Jan_02_2024 # only convnets mlps bn act
#       - GCN_ZINC_GPU-1_00h42m35s_on_Jan_02_2024 # only convnets mlps with act
#       - GCN_ZINC_GPU-1_00h42m57s_on_Jan_02_2024 # only convnets mlps with act
#       - GCN_ZINC_GPU-1_00h52m04s_on_Jan_02_2024 # only convnets mlps with act and residual <- this brakes
#       - GCN_ZINC_GPU-1_00h53m17s_on_Jan_02_2024 # only convnets mlps bn act
#      - GCN_ZINC_GPU-1_00h59m00s_on_Jan_02_2024 # just without residuals
#      - GCN_ZINC_GPU-1_00h57m30s_on_Jan_02_2024 # just without residuals


# TODO: Incorporate the following into different config files
save_aligned: True
deterministic: True
hydra_base_dir: ""
device: cpu
batch_size: 10
num_batches: 1
gw_batch_scaling: 1
geom_ensemble_type: acts # acts or weights
gpu_id: -1
# Whether to update the activations after aligning the weights
update_acts: True
# Whether to compute the histogram based on weight importance
importance: False
# Whether to return a normalised histogram
unbalanced: True
skip_last_layer: True
ensemble_step: 0.5
skip_last_layer_type: 'average' # or 'second'
correction: True
debug: True
past_correction: True
width_ratio: 1
ot_fusions_per_model: 5

# Fine tuning fused models
fine_tune: True
fine_tune_epochs: 50
fine_tune_save_step: 5
