wandb: False
wandb_entity: deep-talk
wandb_project: GCN_Fusion

# Config Directory:
config_dir: ../../../src/conf/models/optimization_models/

# Models path 
models_dir: ../../../models

Dataset: ["ZINC"]
dataset_dir: ../../../gnn_benchmarking/data/molecules/

device : "cpu"
hydra_base_dir: ""